#!/usr/bin/env python3

import json
import argparse
import os
import yaml

def generate_kustomize(state_file, overlay_dir, base_path):
    # 1. Read the curated state file
    with open(state_file, 'r') as f:
        state = json.load(f)

    # 2. Setup Overlay directory
    if not os.path.exists(overlay_dir):
        os.makedirs(overlay_dir)

    kustomization = {
        "apiVersion": "kustomize.config.k8s.io/v1beta1",
        "kind": "Kustomization",
        "resources": [base_path],
        "patches": []
    }

    # Track resources we generate so we can add them to kustomization.yaml
    generated_resources = []

    # 3. Iterate over the PVs that have DR replication data
    for pv_name, pv_data in state.get('persistent_volumes', {}).items():
        dr_info = pv_data.get('dr_replication')
        claim_ref = pv_data.get('claim_ref', {})
        
        if not dr_info or not claim_ref.get('name'):
            continue # Skip volumes that aren't replicated or aren't bound

        pvc_name = claim_ref['name']
        pvc_namespace = claim_ref['namespace']
        dr_vol_id = dr_info['remote_volume_id']
        
        # We need a new name for the imported PV to avoid conflicts if the cluster had history
        new_pv_name = f"dr-imported-{pvc_name}"

        # A. Create the Static PV representing the DR volume
        # We map the CSI volumeHandle directly to the remote SolidFire Volume ID
        static_pv = {
            "apiVersion": "v1",
            "kind": "PersistentVolume",
            "metadata": {
                "name": new_pv_name
            },
            "spec": {
                "capacity": pv_data.get('capacity', {}),
                "accessModes": pv_data.get('access_modes', ["ReadWriteOnce"]),
                "persistentVolumeReclaimPolicy": "Retain",
                "storageClassName": pv_data.get('storage_class', ''),
                "csi": {
                    "driver": "csi.solidfire.com",
                    "volumeHandle": str(dr_vol_id)
                }
            }
        }
        
        pv_filename = f"pv-{pvc_namespace}-{pvc_name}.yaml"
        pv_filepath = os.path.join(overlay_dir, pv_filename)
        with open(pv_filepath, 'w') as f:
            yaml.dump(static_pv, f, default_flow_style=False)
        generated_resources.append(pv_filename)

        # B. Create the Kustomize Patch to hijack the original PVC
        # This forces the original PVC definition (from base) to bind to our new static PV
        pvc_patch = {
            "apiVersion": "v1",
            "kind": "PersistentVolumeClaim",
            "metadata": {
                "name": pvc_name,
                "namespace": pvc_namespace
            },
            "spec": {
                "volumeName": new_pv_name
            }
        }
        
        patch_filename = f"patch-pvc-{pvc_namespace}-{pvc_name}.yaml"
        patch_filepath = os.path.join(overlay_dir, patch_filename)
        with open(patch_filepath, 'w') as f:
            yaml.dump(pvc_patch, f, default_flow_style=False)
        
        # Add patch reference to kustomization
        kustomization['patches'].append({
            "path": patch_filename,
            "target": {
                "kind": "PersistentVolumeClaim",
                "name": pvc_name,
                "namespace": pvc_namespace
            }
        })

    kustomization['resources'].extend(generated_resources)

    # 4. Write the kustomization.yaml file
    kustomize_filepath = os.path.join(overlay_dir, 'kustomization.yaml')
    with open(kustomize_filepath, 'w') as f:
        yaml.dump(kustomization, f, default_flow_style=False, sort_keys=False)

    print(f"Success! Generated Kustomize overlay in '{overlay_dir}'")
    print(f"To apply: kubectl apply -k {overlay_dir}/")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Generate Kustomize DR overlay from SolidFire state JSON.")
    parser.add_argument("--state", required=True, help="Path to the JSON state file generated by export script")
    parser.add_argument("--overlay", default="dr-overlay", help="Directory to output the Kustomize overlay")
    parser.add_argument("--base", default="../base", help="Relative path to the GitOps base resources")
    
    args = parser.parse_args()
    
    generate_kustomize(args.state, args.overlay, args.base)
